// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-Pw5JGxzLAl8VrIHkBkYqGriRl6bJUk',
    appId: '1:453106919709:web:02b08f3d9d7f330c9bd9f4',
    messagingSenderId: '453106919709',
    projectId: 'learn-firebase-cb833',
    authDomain: 'learn-firebase-cb833.firebaseapp.com',
    storageBucket: 'learn-firebase-cb833.appspot.com',
    measurementId: 'G-29Y4H5EHE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJij9iLpDQpSn3Z3PkbwO4NSI4YeHjabI',
    appId: '1:453106919709:android:85da311c9e5331cd9bd9f4',
    messagingSenderId: '453106919709',
    projectId: 'learn-firebase-cb833',
    storageBucket: 'learn-firebase-cb833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPsjy2d7PcbRSb84xbex3ScCYIzGS_bU',
    appId: '1:453106919709:ios:601a24e4a529704a9bd9f4',
    messagingSenderId: '453106919709',
    projectId: 'learn-firebase-cb833',
    storageBucket: 'learn-firebase-cb833.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPsjy2d7PcbRSb84xbex3ScCYIzGS_bU',
    appId: '1:453106919709:ios:601a24e4a529704a9bd9f4',
    messagingSenderId: '453106919709',
    projectId: 'learn-firebase-cb833',
    storageBucket: 'learn-firebase-cb833.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh-Pw5JGxzLAl8VrIHkBkYqGriRl6bJUk',
    appId: '1:453106919709:web:0f93ec4f5fe4ac399bd9f4',
    messagingSenderId: '453106919709',
    projectId: 'learn-firebase-cb833',
    authDomain: 'learn-firebase-cb833.firebaseapp.com',
    storageBucket: 'learn-firebase-cb833.appspot.com',
    measurementId: 'G-VWTGB456WF',
  );
}
